- hosts: music-server
  become: true

  roles:
    - alsa
    - snapcast-server
    - snapcast-client
    - mpd-server

- hosts: music-client
  become: true

  roles:
    - alsa
    - snapcast-client
