---
- name: "install required software from apt"
  apt:
    name: "{{ item }}"
  with_items:
    - "python"
    - "python-pip"
    - "bluez"
    - "bluez-hcidump"

- name: "install python libraries"
  pip:
    name: "{{ item }}"
  with_items:
    - "ruuvitag_sensor"
    - "influxdb"

- name: "install temperature reading script"
  become_user: "{{ ansible_user }}"
  become: true
  template:
    src: "ruuvitag-influxdb.py.j2"
    dest: "{{ script_install_path }}ruuvitag-influxdb.py"

- name: "add temperature reading to cron"
  cron:
    name: "read all ruuvitags to influxdb"
    job: "/usr/bin/python {{ script_install_path }}ruuvitag-influxdb.py"
    minute: "*/6"
    user: "{{ ansible_user }}"

- name: "run temperature reading for the first time"
  become_user: "{{ ansible_user }}"
  become: true
  shell: "/usr/bin/python {{ script_install_path }}ruuvitag-influxdb.py"
